apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- overrides/database.yaml
- overrides/backend.yaml
- overrides/frontend.yaml
images:
  - name: my-backend
    newTag: dev
  - name: my-frontend
    newTag: dev
